name: ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos 
      COMMIT: ${{ github.sha }}
      REPO: carts
    steps:
    - uses: actions/checkout@v2


    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
 
    #
    #
    # Build
    - name: Build jar files
      run: ./scripts/build.sh

    #
    #
   
    - name: Login to DockerHub
      run: |
          echo "${{ secrets.DOCKERHUB_PASS }}" | docker login -u "venupj" --password-stdin 
        
    - name: dir
      run: pwd
    - name: Push to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v5
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      with:
        dockerfile: /home/runner/work/carts/carts/Dockerfile
        path: target/
        registry: docker.io
        image: venupj/sockshop
          #tag_with_ref:true
          #tag_with_sha:true
          
    






