name: ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags
  pull_request:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GROUP: weaveworksdemos 
      COMMIT: ${{ github.sha }}
      REPO: carts
    steps:
    - uses: actions/checkout@v2


    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
 
    #
    #
    # Build
    - name: Build jar files
      run: ./scripts/build.sh

    #
    #
    # Push to dockerhub
    -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
    -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          dockerfile: docker/carts/Dockerfile
          push: true
          tags: user/app:latest






